
var Tag = ['', '2-sat', 'binary search', 'bitmasks', 'brute force',
  'chinese remainder theorem', 'combinatorics', 'constructive algorithms',
  'data structures', 'dfs and similar', 'divide and conquer', 'dp', 'dsu',
  'expression parsing', 'fft', 'flows', 'games', 'geometry', 'graph matchings',
  'graphs', 'greedy', 'hashing', 'implementation', 'math', 'matrices',
  'meet-in-the-middle', 'number theory', 'probabilities', 'schedules',
  'shortest paths', 'sortings', 'string suffix structures', 'strings',
  'ternary search', 'trees', 'two pointers'
];

var ProTil = ['', '2-satisfiability', 'Binary search', 'Bitmasks', 'Brute force',
  'Сhinese remainder theorem', 'Combinatorics', 'Constructive algorithms',
  'Heaps, binary search trees, segment trees, hash tables, etc', 'Dfs and similar',
  'Divide and Conquer', 'Dynamic programming', 'Disjoint set union',
  'Parsing expression grammar', 'Fast Fourier transform', 'Graph network flows',
  'Games, Sprague–Grundy theorem', 'Geometry, computational geometry',
  'Graph matchings, König\'s theorem, vertex cover of bipartite graph', 'Graphs',
  'Greedy algorithms', 'Hashing, hashtables',
  'Implementation problems, programming technics, simulation',
  'Mathematics including integration, differential equations, etc',
  'Matrix multiplication, determinant, Cramer\'s rule, systems of linear equations',
  'Meet-in-the-middle', 'Number theory: Euler function, GCD, divisibility, etc',
  'Probabilities, expected values, statistics, random variables, etc',
  'Scheduling Algorithms', 'Shortest paths on weighted and unweighted graphs',
  'Sortings, orderings', 'Suffix arrays, suffix trees, suffix automatas, etc',
  'Prefix- and Z-functions, suffix structures, Knuth–Morris–Pratt algorithm, etc',
  'Ternary search', 'Trees', 'Two pointers'
];

module.exports = {
  cookie_secret: 'gzhu',
  db: 'mongodb://127.0.0.1:27017/acdream_db',
  reg_close_time: 300000/* 在比赛开始前多少毫秒关闭注册 */,
  problemset_pageNum: 50,
  status_pageNum: 20,
  ranklist_pageNum: 20,
  standings_pageNum: 50,
  contest_pageNum: 20,
  regform_pageNum: 20,
  stats_pageNum: 20,
  contestRank_pageNum: 50,
  topic_pageNum: 15,
  comment_pageNum: 20,
  root_path: __dirname + '/',
  data_path: __dirname + '/data/',
  T: Tag,
  P: ProTil,
  languages: ['All', 'C', 'C++'], //, 'Java'],
  xss_options: {
    whiteList: {
      a: ['target', 'href', 'title', 'id', 'name'],
      blockquote: ['cite'],
      br: [],
      b: [],
      caption: [],
      dd: [],
      div: ['style'],
      dl: [],
      dt: [],
      em: [],
      font: ['color', 'size', 'face'],
      footer: [],
      h1: ['style'],
      h2: ['style'],
      h3: ['style'],
      header: [],
      hr: [],
      i: [],
      img: ['style', 'src', 'alt'],
      li: ['style'],
      ol: [],
      p: ['style'],
      pre: ['style', 'class'],
      section: [],
      small: [],
      span: ['style', 'class'],
      strong: [],
      table: ['style', 'class', 'cellpadding', 'cellspacing', 'summary', 'width', 'border', 'align', 'valign'],
      tbody: ['align', 'valign'],
      td: ['style', 'width', 'colspan', 'align', 'valign'],
      tfoot: ['align', 'valign'],
      th: ['width', 'colspan', 'align', 'valign', 'scope'],
      thead: ['align', 'valign'],
      tr: ['rowspan', 'align', 'valign'],
      ul: []
    }
  }
};
